stages:
  generate_dataset:
    cmd: python -m src.data.generate_dataset

    deps:
      - data/raw/splined_trajectories_3.txt
      - src/data/generate_dataset.py
      - src/data/renderer.py

    params:
      - seed
      - dataset
      - renderer

    outs:
      - data/processed