seed: 42

device:
  use_cuda: true

training:
  epochs: 50
  batch_size: 8
  learning_rate: 0.001
  num_workers: 0

  teacher_forcing:
    start: 1.0
    end: 0.2

model:
  feature_dim: 128
  hidden_dim: 128
  dropout: 0.2

dataset:
  processed_dir: "data/processed"

  train_file: "train.pt"
  val_file: "val.pt"
  test_file: "test.pt"

  image_size: 128
  sequence_length: 21

  train_split: 0.7
  val_split: 0.15
  test_split: 0.15

renderer:
  xlim: [-0.8, 0.8]
  ylim: [-0.8, 0.8]

  arm_radius: 4
  target_size: 6

logging:
  experiment_name: "cnn_lstm_autoregression"